### ISSUE TITLE
Failed to load dynamic library 'libflutter_opengl_plugin.so'

### ISSUE THREAD

**Issue by cwww24** [alnitak/flutter_opengl#10]
Hello brother, I Fork the source code, according to the tutorial to run the example code after the prompt 'Failed to load dynamic library 'libflutter_opengl_plugin.so', I tried for a long time, still can not solve, Did I miss some steps? It's still the same problem when I introduced flutter_opengl from pub to new projects, I think I missed something, but I didn't find another way in the tutorial, can you help me solve it

**Comment by alnitak** [comment]
Hi,

can you please copy/paste some relevant log errors? Are you trying on Linux right?

Anyway, I almost abandoned this project because of the incoming support for OpenGL by the Flutter team.

**Comment by xiaweizi** [comment]
```
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_opengl_plugin.so': dlopen failed: library "libopencv_java4.so" not found: needed by /data/app/~~9Gb3uLkP959jAfYTyvHxGA==/com.example.flutter_opengl_example-Gf4QUz23KLujePboD7LJRQ==/base.apk!/lib/arm64-v8a/libflutter_opengl_plugin.so in namespace clns-4
 #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
 #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
 #2      OpenGLController.initializeGL (package:flutter_opengl/src/opengl_controller.dart:21)
 #3      main (package:flutter_opengl_example/main.dart:5)
 #4      _runMain.<anonymous closure> (dart:ui/hooks.dart:301)
 #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
 #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by alnitak** [comment]
Have you followed the instructions [here](https://github.com/alnitak/flutter_opengl/commit/50b8cd3139ad5ff883109e8307dca3babad72e3b)?
