### ISSUE TITLE
You are amazing

### ISSUE THREAD

**Issue by q384264619** [alnitak/flutter_opengl#4]
This project is really great. It allows independent implementation of OpenGL in Flutter, eliminating the need to use native Java/Objective-C to handle OpenGL logic. You are amazing! But when will the iOS version be released? Looking forward to it!

**Comment by alnitak** [comment]
Hi and thank you very much!

The main problem to have a mac/iOS version is that I do not have a mac/iPhone :smiling_face_with_tear: 
The other problem is that Apple discontinued the support to OpenGL in favor of Metal. It s still possible to install OpenGL but I don't think it's a good way to do this. Another way to add support  for mac/iOS to this plugin, is to adopt [Google Angle](https://github.com/google/angle) which supports also WebGL but I didn't deeply studied it.

**Comment by jtkeyva** [comment]
yes @alnitak this is really great stuff! you can get a used iphone for pretty cheap...but then i suppose you would need a mac too. hmm. your link says don't buy me a coffee haha. well, this would be great to bring to other platforms one day

**Comment by jtkeyva** [comment]
@alnitak i came across this package which uses shaders and also works on web and ios. i don't know about open gl or any of that stuff, but figured this may shed some light on shaders on ios and web ?

https://pub.dev/packages/animated_glitch

i have confirmed that both shader and non shader version works on ios and web

**Comment by anonfaded** [comment]
> Another way to add support for mac/iOS to this plugin, is to adopt [Google Angle](https://github.com/google/angle) which supports also WebGL but I didn't deeply studied it.

hey i wanted to ask that is your this project not working anymore for android? I tried other flutter opengl packages none worked, this one also was not working. The initialization was failing no matter what i did, now i tried the `flutter_angle`, it initialized opengl but another issue i faced now and it is with their package so I'm locked up now and can't proceed with my project. Do you have any clue on how your package can be updated so it works?

the issue with the angle package is this btw:

```bash
[ANGLE TEST] ANGLE init failed: type 'Null' is not a subtype of type 'bool'
#0      FlutterAngle.init (package:flutter_angle/desktop/angle.dart:121:19)
<asynchronous suspension>
#1      _MyAppState._initAngle (package:angle_test/main.dart:25:7)
<asynchronous suspension>
```

And with your project the error was this i guess:

```bash
[Renderer] !!! ERROR DURING GL SETUP !!!: NoSuchMethodError: The getter 'bufferId' was called on null.
Receiver: null
Tried calling: bufferId
```

**Comment by alnitak** [comment]
@anonfaded It's been a long time since this plugin was updated and it's now deprecated on pub.dev. I started maybe in 2019 and a lot has changed in Flutter core. 

I can't help you, but if you're looking to play with shaders, you can take look at [shader_buffers](https://pub.dev/packages/shader_buffers) or [Flutter-GPU](https://github.com/flutter/engine/blob/main/docs/impeller/Flutter-GPU.md) and if you're curious about how the Flutter team is doing with 3D development, you can look at [flutter_scene](https://pub.dev/packages/flutter_scene) by @bdero
